name: Disable Copilot PR Suggestions
on:
  push:
    # You can restrict this to just your default branch if you like:
    branches:
      - main
      - master

permissions:
  administration: write  # needed to update repo settings via GraphQL

jobs:
  disable-copilot-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Disable Copilot pull-request suggestions
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // fetch this repository’s GraphQL node ID
            const { data } = await github.graphql(
              `
              query RepoID($owner:String!, $name:String!) {
                repository(owner:$owner, name:$name) { id }
              }
              `,
              { owner: context.repo.owner, name: context.repo.repo }
            );

            // run the mutation to turn off copilotPullRequestsEnabled
            await github.graphql(
              `
              mutation DisableCopilotPRs($id:ID!) {
                updateRepository(
                  input: { repositoryId: $id, copilotPullRequestsEnabled: false }
                ) {
                  repository { nameWithOwner }
                }
              }
              `,
              { id: data.repository.id }
            );

            console.log(`✅ Copilot PRs disabled for ${context.repo.owner}/${context.repo.repo}`);
